server:
  port: 8701 # 服务消费方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka
  instance:
    hostname: localhost

#当前服务名称
spring:
  application:
    name: zuul


management:
  endpoints:
    web:
      exposure:
        include: "*"
      #添加需要暴露出去的路径，"*"表示所有路径


#路由规则定义。这里定义两种路由规则route1和route2
#，代表访问网关/test01/**或/test02/**时。
#路由到服务名为 eureka-service-shop中的服务集群去。
zuul:
  host:
    socket-timeout-millis: 12000
    connect-timeout-millis: 12000
  routes:
    route1:
      path: /test01/**
      serviceId: eureka-service-shop
    route2:
      path: /test02/**
      serviceId: eureka-service-shop2

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 12000
  eureka:
    enabled: true
