#当前服务名称
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: eureka-service-shop           #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          uri: http://localhost:8800  #匹配后提供服务的路由地址
          predicates:
            - Path=/center/**    #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1   #去掉一级，业务服务yml中没有配置servlet:context-path就需要加上这个

        - id: eureka-service-shop_2         #路由的ID，没有固定规则但要求统一，建议配合服务名
          uri: lb://eureka-service-shop #匹配后提供服务的内部服务,这里用服务名称
          predicates:
            - Path=/center2/**     #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去掉一级，业务服务yml中没有配置servlet:context-path就需要加上这个

server:
  port: 8080 # 路由地址


# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka
  instance:
    hostname: localhost
